export type Level = 'A1' | 'A2';

export interface DirectionCard {
  id: number;
  phrase: string;            // German word or phrase
  translation: string;       // English translation
  emoji: string;
  example: string;           // Mannheim-specific German example sentence
  exampleTranslation: string;
  level: Level;
}

export const directions: DirectionCard[] = [
  // ── A1: Basic direction words ──
  {
    id: 1,
    phrase: 'geradeaus',
    translation: 'straight ahead',
    emoji: '⬆️',
    example: 'Der Wasserturm ist geradeaus.',
    exampleTranslation: 'The water tower is straight ahead.',
    level: 'A1',
  },
  {
    id: 2,
    phrase: 'links',
    translation: 'left',
    emoji: '⬅️',
    example: 'Das Schloss ist links.',
    exampleTranslation: 'The palace is on the left.',
    level: 'A1',
  },
  {
    id: 3,
    phrase: 'rechts',
    translation: 'right',
    emoji: '➡️',
    example: 'Der Bahnhof ist rechts.',
    exampleTranslation: 'The station is on the right.',
    level: 'A1',
  },
  {
    id: 4,
    phrase: 'neben',
    translation: 'next to',
    emoji: '📍',
    example: 'Die Apotheke ist neben dem Supermarkt.',
    exampleTranslation: 'The pharmacy is next to the supermarket.',
    level: 'A1',
  },
  {
    id: 5,
    phrase: 'gegenüber',
    translation: 'opposite / across from',
    emoji: '🔄',
    example: 'Das Café ist gegenüber dem Bahnhof.',
    exampleTranslation: 'The café is opposite the station.',
    level: 'A1',
  },
  {
    id: 6,
    phrase: 'zwischen',
    translation: 'between',
    emoji: '↔️',
    example: 'Das Hotel liegt zwischen Quadrat B4 und C4.',
    exampleTranslation: 'The hotel is between square B4 and C4.',
    level: 'A1',
  },
  {
    id: 7,
    phrase: 'in der Nähe',
    translation: 'nearby / close to',
    emoji: '🗺️',
    example: 'Das Café ist in der Nähe vom Wasserturm.',
    exampleTranslation: 'The café is near the water tower.',
    level: 'A1',
  },
  {
    id: 8,
    phrase: 'um die Ecke',
    translation: 'around the corner',
    emoji: '🔀',
    example: 'Die Bäckerei ist um die Ecke.',
    exampleTranslation: 'The bakery is around the corner.',
    level: 'A1',
  },
  {
    id: 9,
    phrase: 'weit',
    translation: 'far',
    emoji: '📏',
    example: 'Der Hauptbahnhof ist nicht weit von hier.',
    exampleTranslation: 'The main station is not far from here.',
    level: 'A1',
  },
  {
    id: 10,
    phrase: 'hier',
    translation: 'here',
    emoji: '📌',
    example: 'Wir sind hier, am Quadrat B3.',
    exampleTranslation: 'We are here, at square B3.',
    level: 'A1',
  },

  // ── A2: Full direction phrases ──
  {
    id: 11,
    phrase: 'Biegen Sie links ab.',
    translation: 'Turn left.',
    emoji: '↩️',
    example: 'Biegen Sie an der Ampel links ab.',
    exampleTranslation: 'Turn left at the traffic light.',
    level: 'A2',
  },
  {
    id: 12,
    phrase: 'Biegen Sie rechts ab.',
    translation: 'Turn right.',
    emoji: '↪️',
    example: 'Biegen Sie am Wasserturm rechts ab.',
    exampleTranslation: 'Turn right at the water tower.',
    level: 'A2',
  },
  {
    id: 13,
    phrase: 'Gehen Sie geradeaus.',
    translation: 'Go straight ahead.',
    emoji: '🚶',
    example: 'Gehen Sie geradeaus bis zum Paradeplatz.',
    exampleTranslation: 'Go straight ahead until Paradeplatz.',
    level: 'A2',
  },
  {
    id: 14,
    phrase: 'auf der linken Seite',
    translation: 'on the left side',
    emoji: '👈',
    example: 'Das Schloss ist auf der linken Seite.',
    exampleTranslation: 'The palace is on the left side.',
    level: 'A2',
  },
  {
    id: 15,
    phrase: 'auf der rechten Seite',
    translation: 'on the right side',
    emoji: '👉',
    example: 'Der Wasserturm ist auf der rechten Seite.',
    exampleTranslation: 'The water tower is on the right side.',
    level: 'A2',
  },
  {
    id: 16,
    phrase: 'an der nächsten Kreuzung',
    translation: 'at the next intersection',
    emoji: '🚦',
    example: 'Biegen Sie an der nächsten Kreuzung rechts ab.',
    exampleTranslation: 'Turn right at the next intersection.',
    level: 'A2',
  },
  {
    id: 17,
    phrase: 'an der Ampel',
    translation: 'at the traffic light',
    emoji: '🚥',
    example: 'Warten Sie an der Ampel und dann gehen Sie links.',
    exampleTranslation: 'Wait at the traffic light and then go left.',
    level: 'A2',
  },
  {
    id: 18,
    phrase: 'Sie können es nicht verpassen.',
    translation: "You can't miss it.",
    emoji: '🎯',
    example: 'Der Wasserturm ist sehr groß — Sie können ihn nicht verpassen!',
    exampleTranslation: "The water tower is very big — you can't miss it!",
    level: 'A2',
  },
  {
    id: 19,
    phrase: 'Wie komme ich zum ...?',
    translation: 'How do I get to ...?',
    emoji: '❓',
    example: 'Entschuldigung, wie komme ich zum Hauptbahnhof?',
    exampleTranslation: 'Excuse me, how do I get to the main station?',
    level: 'A2',
  },
  {
    id: 20,
    phrase: 'ungefähr fünf Minuten zu Fuß',
    translation: 'about five minutes on foot',
    emoji: '🦶',
    example: 'Der Marktplatz ist ungefähr fünf Minuten zu Fuß vom Bahnhof.',
    exampleTranslation: 'The market square is about five minutes on foot from the station.',
    level: 'A2',
  },
];
