export interface OrderScenario {
  id: string;
  emoji: string;
  setting: string;      // location context
  prompt: string;       // English instruction shown to learner
  targetPhrase: string; // German phrase they should say
  keywords: string[];   // lowercase words that must appear in transcript
  level: 'A1' | 'A2' | 'B1';
}

export const orders: OrderScenario[] = [
  // ── A1: Simple single-item orders ──
  {
    id: 'kaffee',
    emoji: '☕',
    setting: 'Café am Wasserturm',
    prompt: 'Order a coffee',
    targetPhrase: 'Einen Kaffee, bitte.',
    keywords: ['kaffee'],
    level: 'A1',
  },
  {
    id: 'weck',
    emoji: '🍞',
    setting: 'Bäckerei in der Innenstadt',
    prompt: 'Order a bread roll',
    targetPhrase: 'Einen Weck, bitte.',
    keywords: ['weck'],
    level: 'A1',
  },
  {
    id: 'wasser',
    emoji: '💧',
    setting: 'Restaurant am Paradeplatz',
    prompt: 'Order a glass of water',
    targetPhrase: 'Ein Wasser, bitte.',
    keywords: ['wasser'],
    level: 'A1',
  },
  {
    id: 'rechnung',
    emoji: '🧾',
    setting: 'Restaurant im Quadrat C4',
    prompt: 'Ask for the bill',
    targetPhrase: 'Die Rechnung, bitte.',
    keywords: ['rechnung'],
    level: 'A1',
  },
  {
    id: 'tee',
    emoji: '🍵',
    setting: 'Café in der Breiten Straße',
    prompt: 'Order a tea',
    targetPhrase: 'Einen Tee, bitte.',
    keywords: ['tee'],
    level: 'A1',
  },
  {
    id: 'kuchen',
    emoji: '🍰',
    setting: 'Café am Marktplatz',
    prompt: 'Order a piece of cake',
    targetPhrase: 'Ein Stück Kuchen, bitte.',
    keywords: ['kuchen'],
    level: 'A1',
  },
  {
    id: 'speisekarte',
    emoji: '📋',
    setting: 'Restaurant in der Kunststraße',
    prompt: 'Ask for the menu',
    targetPhrase: 'Die Speisekarte, bitte.',
    keywords: ['speisekarte'],
    level: 'A1',
  },
  {
    id: 'toilette',
    emoji: '🚻',
    setting: 'Restaurant im Quadrat E3',
    prompt: 'Ask where the toilet is',
    targetPhrase: 'Wo ist die Toilette, bitte?',
    keywords: ['toilette'],
    level: 'A1',
  },
  {
    id: 'was-kostet',
    emoji: '💶',
    setting: 'Bäckerei am Hauptbahnhof',
    prompt: 'Ask how much the bread roll costs',
    targetPhrase: 'Was kostet der Weck?',
    keywords: ['kostet', 'weck'],
    level: 'A1',
  },
  {
    id: 'danke-tschuss',
    emoji: '👋',
    setting: 'Café am Wasserturm',
    prompt: 'Say thank you and goodbye',
    targetPhrase: 'Danke schön. Auf Wiedersehen!',
    keywords: ['danke', 'wiedersehen'],
    level: 'A1',
  },

  // ── A2: Multi-item orders and questions ──
  {
    id: 'kaffee-brezel',
    emoji: '☕',
    setting: 'Café neben dem Schloss',
    prompt: 'Order a coffee and a pretzel',
    targetPhrase: 'Einen Kaffee und eine Brezel, bitte.',
    keywords: ['kaffee', 'brezel'],
    level: 'A2',
  },
  {
    id: 'schnitzel-bier',
    emoji: '🍖',
    setting: 'Biergarten am Neckar',
    prompt: 'Order a schnitzel and a beer',
    targetPhrase: 'Ein Schnitzel und ein Bier, bitte.',
    keywords: ['schnitzel', 'bier'],
    level: 'A2',
  },
  {
    id: 'spargel',
    emoji: '🌱',
    setting: 'Markt am Quadrat E5',
    prompt: 'Ask if they have asparagus',
    targetPhrase: 'Haben Sie Spargel?',
    keywords: ['spargel'],
    level: 'A2',
  },
  {
    id: 'empfehlung',
    emoji: '👨‍🍳',
    setting: 'Restaurant in der Kunststraße',
    prompt: 'Ask what they recommend',
    targetPhrase: 'Was empfehlen Sie?',
    keywords: ['empfehlen'],
    level: 'A2',
  },
  {
    id: 'kaffee-milch',
    emoji: '🥛',
    setting: 'Café am Wasserturm',
    prompt: 'Ask for a coffee with milk',
    targetPhrase: 'Einen Kaffee mit Milch, bitte.',
    keywords: ['kaffee', 'milch'],
    level: 'A2',
  },
  {
    id: 'vegetarisch',
    emoji: '🥗',
    setting: 'Restaurant am Marktplatz',
    prompt: 'Ask if there is something vegetarian on the menu',
    targetPhrase: 'Haben Sie etwas Vegetarisches?',
    keywords: ['vegetarisch'],
    level: 'A2',
  },
  {
    id: 'mitnehmen',
    emoji: '🥡',
    setting: 'Imbiss in der Innenstadt',
    prompt: 'Say you want to take your order to go',
    targetPhrase: 'Ich möchte das mitnehmen.',
    keywords: ['mitnehmen'],
    level: 'A2',
  },
  {
    id: 'tisch-reservieren',
    emoji: '🪑',
    setting: 'Restaurant im Quadrat D2',
    prompt: 'Reserve a table for two people this evening',
    targetPhrase: 'Ich möchte einen Tisch für zwei Personen reservieren.',
    keywords: ['tisch', 'reservieren', 'personen'],
    level: 'A2',
  },
  {
    id: 'tagesmenü',
    emoji: '🍽️',
    setting: 'Mittagsrestaurant am Friedrichsplatz',
    prompt: 'Ask what the daily special is today',
    targetPhrase: 'Was ist das Tagesmenü heute?',
    keywords: ['tagesmenü'],
    level: 'A2',
  },
  {
    id: 'karte-zahlen',
    emoji: '💳',
    setting: 'Restaurant in der Kunststraße',
    prompt: 'Ask if you can pay by card',
    targetPhrase: 'Kann ich mit Karte zahlen?',
    keywords: ['karte', 'zahlen'],
    level: 'A2',
  },
  {
    id: 'wlan-passwort',
    emoji: '📶',
    setting: 'Café am Wasserturm',
    prompt: 'Ask for the WiFi password',
    targetPhrase: 'Was ist das WLAN-Passwort, bitte?',
    keywords: ['wlan', 'passwort'],
    level: 'A2',
  },
  {
    id: 'getrennt-zahlen',
    emoji: '🧾',
    setting: 'Restaurant mit Freunden',
    prompt: 'Ask to pay separately',
    targetPhrase: 'Wir möchten getrennt zahlen, bitte.',
    keywords: ['getrennt', 'zahlen'],
    level: 'A2',
  },
  {
    id: 'tagessuppe',
    emoji: '🍲',
    setting: 'Café-Restaurant am Neckar',
    prompt: 'Ask what the soup of the day is',
    targetPhrase: 'Was ist die Tagessuppe?',
    keywords: ['tagessuppe'],
    level: 'A2',
  },
  {
    id: 'zwei-bier',
    emoji: '🍺',
    setting: 'Biergarten im Luisenpark',
    prompt: 'Order two beers',
    targetPhrase: 'Zwei Bier, bitte.',
    keywords: ['zwei', 'bier'],
    level: 'A2',
  },
  {
    id: 'kein-fleisch',
    emoji: '🚫',
    setting: 'Restaurant am Paradeplatz',
    prompt: 'Tell the waiter you do not eat meat',
    targetPhrase: 'Ich esse kein Fleisch.',
    keywords: ['fleisch'],
    level: 'A2',
  },
  {
    id: 'wo-toilette',
    emoji: '🚻',
    setting: 'Großes Restaurant in der Innenstadt',
    prompt: 'Politely ask where the toilets are',
    targetPhrase: 'Entschuldigung, wo sind die Toiletten?',
    keywords: ['toiletten'],
    level: 'A2',
  },

  // ── B1: Real-life administrative and complex scenarios ──
  {
    id: 'arzttermin',
    emoji: '🏥',
    setting: 'Arztpraxis — Anmeldung',
    prompt: 'Make a doctor\'s appointment for next week — you have a sore throat',
    targetPhrase: 'Ich hätte gerne einen Termin nächste Woche. Ich habe Halsschmerzen.',
    keywords: ['termin', 'halsschmerzen'],
    level: 'B1',
  },
  {
    id: 'rezept-abgeben',
    emoji: '💊',
    setting: 'Apotheke am Wasserturm',
    prompt: 'Hand in a prescription and ask how many times a day to take the tablets',
    targetPhrase: 'Ich habe ein Rezept. Wie oft muss ich die Tabletten täglich nehmen?',
    keywords: ['rezept', 'tabletten', 'nehmen'],
    level: 'B1',
  },
  {
    id: 'falsche-rechnung',
    emoji: '🧾',
    setting: 'Restaurant — Kasse',
    prompt: 'Politely point out there is a mistake — you were charged for something you did not order',
    targetPhrase: 'Entschuldigung, ich glaube, hier ist ein Fehler. Ich habe das nicht bestellt.',
    keywords: ['fehler', 'bestellt'],
    level: 'B1',
  },
  {
    id: 'anmelden-termin',
    emoji: '🏛️',
    setting: 'Einwohnermeldeamt Mannheim',
    prompt: 'Call to make an appointment to register your new address',
    targetPhrase: 'Ich möchte gerne einen Termin zur Anmeldung meiner neuen Adresse vereinbaren.',
    keywords: ['termin', 'anmeldung', 'adresse'],
    level: 'B1',
  },
  {
    id: 'wohnung-anfragen',
    emoji: '🏠',
    setting: 'Telefon — Wohnungsanzeige',
    prompt: 'Call about an apartment — ask if it is still available and when you can view it',
    targetPhrase: 'Ich rufe wegen der Wohnung an. Ist sie noch frei? Wann kann ich sie besichtigen?',
    keywords: ['wohnung', 'besichtigen'],
    level: 'B1',
  },
  {
    id: 'handyvertrag-kündigen',
    emoji: '📱',
    setting: 'Kundenservice-Hotline',
    prompt: 'Cancel your phone contract and ask about the notice period',
    targetPhrase: 'Ich möchte meinen Vertrag kündigen. Wie lange ist die Kündigungsfrist?',
    keywords: ['kündigen', 'kündigungsfrist'],
    level: 'B1',
  },
  {
    id: 'urlaub-beantragen',
    emoji: '✈️',
    setting: 'Büro — Gespräch mit dem Chef',
    prompt: 'Ask your boss if you can take two weeks off in August',
    targetPhrase: 'Ich würde gerne zwei Wochen Urlaub im August nehmen. Ist das möglich?',
    keywords: ['urlaub', 'august'],
    level: 'B1',
  },
  {
    id: 'heizung-kaputt',
    emoji: '🔧',
    setting: 'Telefon — Anruf beim Vermieter',
    prompt: 'Tell your landlord the heating is broken and ask when it can be repaired',
    targetPhrase: 'Die Heizung in meiner Wohnung ist kaputt. Wann kann das repariert werden?',
    keywords: ['heizung', 'kaputt', 'repariert'],
    level: 'B1',
  },
  {
    id: 'aufenthaltserlaubnis',
    emoji: '📄',
    setting: 'Ausländerbehörde Mannheim',
    prompt: 'Ask what documents you need to extend your residence permit',
    targetPhrase: 'Welche Unterlagen brauche ich, um meine Aufenthaltserlaubnis zu verlängern?',
    keywords: ['unterlagen', 'aufenthaltserlaubnis', 'verlängern'],
    level: 'B1',
  },
  {
    id: 'kurs-vhs',
    emoji: '📚',
    setting: 'Volkshochschule Mannheim',
    prompt: 'Ask to sign up for the B2 German course starting next month',
    targetPhrase: 'Ich möchte mich für den Deutschkurs B2 anmelden, der nächsten Monat beginnt.',
    keywords: ['anmelden', 'deutschkurs'],
    level: 'B1',
  },
  {
    id: 'versicherung-karte',
    emoji: '🛡️',
    setting: 'Krankenkasse — Kundentelefon',
    prompt: 'Report that you lost your health insurance card and need a new one sent',
    targetPhrase: 'Ich habe meine Krankenkassenkarte verloren. Können Sie mir eine neue schicken?',
    keywords: ['krankenkassenkarte', 'verloren'],
    level: 'B1',
  },
  {
    id: 'dauerauftrag',
    emoji: '🏦',
    setting: 'Sparkasse Mannheim — Schalter',
    prompt: 'Ask the bank clerk how to set up a standing order',
    targetPhrase: 'Wie kann ich einen Dauerauftrag einrichten?',
    keywords: ['dauerauftrag', 'einrichten'],
    level: 'B1',
  },
  {
    id: 'nebenkosten-frage',
    emoji: '📝',
    setting: 'Wohnungsbesichtigung in Neustadt',
    prompt: 'Ask the landlord whether utilities are included in the rent',
    targetPhrase: 'Sind die Nebenkosten in der Miete inbegriffen?',
    keywords: ['nebenkosten', 'miete'],
    level: 'B1',
  },
];
